[package]
name = "tree-sitter-blade"
description = "a tree-sitter parser for the blade templating language"
version = "0.1.0"
authors = ["Joshua Kellogg"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "blade"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/jkellogg01/tree-sitter-blade"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.1.22"

[dev-dependencies]
tree-sitter = "0.24.3"
